name: "get-assets"
description: "Batch GET UiPath asset values (Text/Integer/Bool) and write assets.values.json"
inputs:
  folder_name:    { description: "X-UIPATH-FolderPath value", required: true }
  asset_filter:  { description: "", required: true }
runs:
  using: "composite"
  steps:


    - name: GET values and build assets.values.json
      shell: bash
      run: |
        set -euo pipefail
        echo "checking release"
        body="$(mktemp)"
        trap 'rm -f "$body"' EXIT

        curl_rc=0
        status=$(
          curl -L -sS \
            --connect-timeout 10 --max-time 120 \
            --output "$body" \
            --write-out '%{http_code}' \
            -H "Authorization: Bearer ${{ env.TOKEN }}" \
            -H "Content-Type: application/json" \
            -H "X-UIPATH-FolderPath: ${{ inputs.folder_name }}" \
            "${{ env.OR_URL }}/odata/Assets/UiPath.Server.Configuration.OData.GetFiltered?%24filter=ValueType%20eq%20%27Text%27%20and%20(${{inputs.asset_filter}})&%24select=Name%2CStringValue"
        ) || curl_rc=$?

        echo "Status Code: $status"
        echo "::group::Response body"
        if [[ -s "$body" ]] && command -v jq >/dev/null && jq -e . "$body" >/dev/null 2>&1; then
          jq -r . "$body"
        else
          cat "$body"
        fi
        echo "::endgroup::"

    - name: GET values and build assets.values.json
      shell: bash
      run: |
        set -euo pipefail
        echo "checking release"
        body="$(mktemp)"
        trap 'rm -f "$body"' EXIT

        curl_rc=0
        status=$(
          curl -L -sS \
            --connect-timeout 10 --max-time 120 \
            --output "$body" \
            --write-out '%{http_code}' \
            -H "Authorization: Bearer ${{ env.TOKEN }}" \
            -H "Content-Type: application/json" \
            -H "X-UIPATH-FolderPath: ${{ inputs.folder_name }}" \
            "${{ env.OR_URL }}/odata/Assets/UiPath.Server.Configuration.OData.GetFiltered?%24filter=ValueType%20eq%20%27Integer%27%20and%20(${{inputs.asset_filter}})&%24select=Name%2CIntValue"
        ) || curl_rc=$?

        echo "Status Code: $status"
        echo "::group::Response body"
        if [[ -s "$body" ]] && command -v jq >/dev/null && jq -e . "$body" >/dev/null 2>&1; then
          jq -r . "$body"
        else
          cat "$body"
        fi
        echo "::endgroup::"

    - name: GET values and build assets.values.json
      shell: bash
      run: |
        set -euo pipefail
        echo "checking release"
        body="$(mktemp)"
        trap 'rm -f "$body"' EXIT

        curl_rc=0
        status=$(
          curl -L -sS \
            --connect-timeout 10 --max-time 120 \
            --output "$body" \
            --write-out '%{http_code}' \
            -H "Authorization: Bearer ${{ env.TOKEN }}" \
            -H "Content-Type: application/json" \
            -H "X-UIPATH-FolderPath: ${{ inputs.folder_name }}" \
            "${{ env.OR_URL }}/odata/Assets/UiPath.Server.Configuration.OData.GetFiltered?%24filter=ValueType%20eq%20%27Bool%27%20and%20(${{inputs.asset_filter}})&%24select=Name%2CBoolValue"
        ) || curl_rc=$?

        echo "Status Code: $status"
        echo "::group::Response body"
        if [[ -s "$body" ]] && command -v jq >/dev/null && jq -e . "$body" >/dev/null 2>&1; then
          jq -r . "$body"
        else
          cat "$body"
        fi
        echo "::endgroup::"
        
    - name: Output path
      id: out
      shell: bash
      run: echo "path=$GITHUB_WORKSPACE/assets.values.json" >> "$GITHUB_OUTPUT"


outputs:
  path:
    description: "Path to assets.values.json"
    value: ${{ steps.out.outputs.path }}
